name: tabmenu
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  custom_rating_bar: ^3.0.0
  flutter:
    sdk: flutter
  flutter_tilt: ^3.2.2
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.9.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
